0.2.x — Expand `peerDependency` for `react` to include v16
modulz/stitches pull request #648
Opened 2021-06-18 13:30 UTC by jonathantneal

This change expands the `peerDependency` coverage for `react` from `>= 17` to `>= 16`.

Resolves https://github.com/modulz/stitches/discussions/647

2021-06-18 14:04 UTC, peduarte approved these changes

2021-06-21 20:29 UTC, rafgraph commented
The `forwardRef` api wasn’t implemented until v16.3, so it might be good to change it to `>= 16.3`, instead of `>= 16`.
https://reactjs.org/blog/2018/03/29/react-v-16-3.html

2021-06-22 07:18 UTC, peduarte commented
@rafgraph that's a good shout! thanks for the heads up 🙏

2021-06-22 07:19 UTC, peduarte requested changes

2021-06-22 07:19 UTC, peduarte commented on packages/react/package.json
> +    "react": ">= 16"
```suggestion
    "react": ">= 16.3.0"
```

2021-06-23 12:25 UTC, peduarte approved these changes

2021-07-07 12:59 UTC, KRRISH96 commented
Hey @peduarte, 

Thanks for the super cool library. ❤️

My team is starting a new project and we decided to use stitches for styling to bring our own design system.
But our `React` codebase is on `v16.4` and this PR is exactly what we needed at the moment.

Seems PR is approved and GTG, any plans on merging this soon? That would be really helpful.

Appreciate your efforts on building this super awesome product.

2021-07-12 07:31 UTC, peduarte commented
@jonathantneal can we get this in and released today?

2021-07-22 16:08 UTC, merged